server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances //the current branch
          uri: https://github.com/juancarlosmop/microservicios-tutorial // url github repository
          search-paths: config-data // the  folder
  application:
      name: config-service
